<a href="https://colab.research.google.com/github/potopinc/colab/blob/main/ML_3_self_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Практика по  NumPy

Этот ноутбук представляет из себя  практическое задание.



В этом блоке нужно выполнить несколько простых упражнений на работу с векторами в numpy.
Пишите код в ячейках после каждого задания. Для начала импортируйте библиотеку.

In [1]:
import numpy as np

Ниже считывается файл с минимальными температурами по дням в период с 01.01.2003 по 25.09.2005 в г. Москва.

In [23]:
with open('weather_min.txt') as f:
  l = f.readlines()
l = np.array([temp[:-1] for temp in l[:-1]])
l = l[l != ''].astype(float)
l

array([-28., -12.,  -9., -12., -19., -28., -30., -29., -21., -24., -28.,
       -26., -11., -15.,  -8.,  -5.,  -3.,  -2.,  -1.,  -2.,  -6.,  -6.,
        -6.,  -8.,  -8.,  -2.,  -2.,  -2.,  -3.,  -2.,  -9., -18., -21.,
       -23., -22., -15., -15., -12.,  -8., -12., -18., -22., -22., -10.,
        -9., -22., -23., -10.,  -8.,  -3., -14., -12.,  -9., -12., -13.,
        -6.,  -6.,  -9., -12., -14., -17., -18., -18., -15., -16., -16.,
       -13., -13.,  -7.,  -5.,  -2.,  -3.,  -5.,  -5.,  -6.,  -8.,  -7.,
        -9.,  -8., -11., -14., -15.,  -5.,  -3., -10., -11.,  -6.,  -3.,
        -2.,   1.,  -5.,  -6.,  -8.,   0.,  -1.,  -1.,   0.,   0.,   0.,
        -3.,  -5.,   0.,   3.,   1.,   0.,   4.,   2.,   2.,   0.,   3.,
         5.,   3.,   3.,   0.,  -6.,  -7.,  -6.,  -3.,   1.,   6.,   5.,
         7.,   5.,   4.,   3.,   2.,   8.,   5.,   3.,  11.,  10.,   9.,
        14.,  16.,  12.,  10.,   3.,   2.,   6.,  10.,  15.,  15.,  12.,
        12.,  12.,  12.,  13.,  12.,   4.,   3.,   

# 1. Январь
Выведите все значения температуры за январь 2003 года.

In [5]:
l[0:31]

array([-28., -12.,  -9., -12., -19., -28., -30., -29., -21., -24., -28.,
       -26., -11., -15.,  -8.,  -5.,  -3.,  -2.,  -1.,  -2.,  -6.,  -6.,
        -6.,  -8.,  -8.,  -2.,  -2.,  -2.,  -3.,  -2.,  -9.])

# 2. Последний день
Измените температуру последнего дня на любое число.

In [25]:
l[-1] = 50
print(l)

[-28. -12.  -9. -12. -19. -28. -30. -29. -21. -24. -28. -26. -11. -15.
  -8.  -5.  -3.  -2.  -1.  -2.  -6.  -6.  -6.  -8.  -8.  -2.  -2.  -2.
  -3.  -2.  -9. -18. -21. -23. -22. -15. -15. -12.  -8. -12. -18. -22.
 -22. -10.  -9. -22. -23. -10.  -8.  -3. -14. -12.  -9. -12. -13.  -6.
  -6.  -9. -12. -14. -17. -18. -18. -15. -16. -16. -13. -13.  -7.  -5.
  -2.  -3.  -5.  -5.  -6.  -8.  -7.  -9.  -8. -11. -14. -15.  -5.  -3.
 -10. -11.  -6.  -3.  -2.   1.  -5.  -6.  -8.   0.  -1.  -1.   0.   0.
   0.  -3.  -5.   0.   3.   1.   0.   4.   2.   2.   0.   3.   5.   3.
   3.   0.  -6.  -7.  -6.  -3.   1.   6.   5.   7.   5.   4.   3.   2.
   8.   5.   3.  11.  10.   9.  14.  16.  12.  10.   3.   2.   6.  10.
  15.  15.  12.  12.  12.  12.  13.  12.   4.   3.   9.   6.   3.   3.
   4.   7.  11.   9.   9.   8.  11.   8.   9.   9.   4.   4.   5.   7.
   6.   7.   5.   9.   8.   9.   8.   8.  10.  12.  10.  10.  10.  12.
  11.  12.  13.  14.  18.  16.  16.  15.  14.  14.  15.  15.  15.  17.
  13. 

# 3. Не люблю холода
Замените все отрицательные температуры на положительные (не изменяя значения температур). Подсказка: np.abs().

In [27]:
l = np.abs(l)
l

array([28., 12.,  9., 12., 19., 28., 30., 29., 21., 24., 28., 26., 11.,
       15.,  8.,  5.,  3.,  2.,  1.,  2.,  6.,  6.,  6.,  8.,  8.,  2.,
        2.,  2.,  3.,  2.,  9., 18., 21., 23., 22., 15., 15., 12.,  8.,
       12., 18., 22., 22., 10.,  9., 22., 23., 10.,  8.,  3., 14., 12.,
        9., 12., 13.,  6.,  6.,  9., 12., 14., 17., 18., 18., 15., 16.,
       16., 13., 13.,  7.,  5.,  2.,  3.,  5.,  5.,  6.,  8.,  7.,  9.,
        8., 11., 14., 15.,  5.,  3., 10., 11.,  6.,  3.,  2.,  1.,  5.,
        6.,  8.,  0.,  1.,  1.,  0.,  0.,  0.,  3.,  5.,  0.,  3.,  1.,
        0.,  4.,  2.,  2.,  0.,  3.,  5.,  3.,  3.,  0.,  6.,  7.,  6.,
        3.,  1.,  6.,  5.,  7.,  5.,  4.,  3.,  2.,  8.,  5.,  3., 11.,
       10.,  9., 14., 16., 12., 10.,  3.,  2.,  6., 10., 15., 15., 12.,
       12., 12., 12., 13., 12.,  4.,  3.,  9.,  6.,  3.,  3.,  4.,  7.,
       11.,  9.,  9.,  8., 11.,  8.,  9.,  9.,  4.,  4.,  5.,  7.,  6.,
        7.,  5.,  9.,  8.,  9.,  8.,  8., 10., 12., 10., 10., 10

#4. Удачное число
Найдите индексы всех чисел равных 7. Подсказка: np.where().

In [29]:
np.where(l == 7)

(array([ 68,  76, 115, 121, 155, 167, 169, 244, 247, 250, 251, 256, 257,
        270, 276, 279, 281, 338, 339, 345, 394, 398, 401, 415, 508, 511,
        588, 590, 591, 610, 625, 699, 713, 718, 747, 777, 832, 834, 856,
        859, 860, 864, 961, 970, 975, 984, 986, 994]),)

# 5. Неудуачное число
Замените все числа, кратные 13 или 4, на число 7.

In [59]:
l = np.where(l % 13 == 0, 7, l)
l = np.where(l % 4 == 0, 7, l)
np.where(l == 7)
l

array([-22.19,  -8.18,  -4.11,  -8.51, -16.01, -23.44, -25.95, -24.99,
       -17.73, -19.53, -24.59, -21.54,  -5.64,  -9.09,  -3.88,   0.13,
         1.22,   1.08,   2.33,   2.79,  -3.18,  -1.73,  -0.9 ,  -2.71,
        -3.75,   3.05,   2.54,   2.3 ,   2.44,   1.76,  -3.56, -14.23,
       -15.63, -18.09, -17.06, -10.95,  -9.86,  -7.73,  -2.23,  -9.6 ,
       -12.52, -18.99, -18.77,  -6.32,  -4.34,   7.  , -19.31,  -6.76,
        -4.6 ,   2.74, -10.1 ,  -9.48,  -4.59,  -7.58,  -9.2 ,  -1.41,
        -1.23,  -5.1 ,  -6.81,  -9.29, -11.7 , -13.13, -13.79, -10.37,
       -12.44, -11.91,  -8.77,  -8.82,  -1.47,  -0.6 ,   2.66,   0.04,
         0.14,   0.49,  -1.64,  -2.39,  -2.81,  -4.49,  -5.44,  -5.48,
       -10.2 ,  -9.67,  -0.32,   0.29,  -5.95,  -7.25,  -1.94,   2.07,
         2.41,   4.93,  -0.34,  -1.73,  -3.49,   4.42,   4.29,   3.85,
         4.98,   3.69,   4.76,   2.65,   0.69,   5.07,   7.74,   5.43,
         4.49,   7.96,   4.38,   6.88,   5.64,   6.94,   9.17,   7.69,
      

#6. Статистика
Найдите минимум, максимум, среднее значение и медиану.

In [35]:
with open('weather_min.txt') as f:
  l = f.readlines()
l = np.array([temp[:-1] for temp in l[:-1]])
l = l[l != ''].astype(float)

In [36]:
min(l)

np.float64(-30.0)

In [37]:
max(l)

np.float64(19.0)

In [39]:
np.median(l)

np.float64(3.0)

In [41]:
round(np.mean(l), 2)

np.float64(1.46)

# 7. Неповторимый
Сколько уникальных значений температур содержит файл? Подсказка: np.unique().

In [45]:
len(np.unique(l))

48

# 8. Глобальное потепление
Увеличьте значение температуры каждого дня на случайное число от 0 до 1 (случайные числа должны быть разными).

In [60]:
l = l + np.random.uniform(0, 1, size = l.shape)
np.set_printoptions(suppress=True)
l = np.round(l, 2)
l

array([-21.34,  -7.35,  -3.59,  -7.8 , -15.91, -22.52, -25.12, -24.26,
       -17.16, -19.09, -24.46, -21.01,  -5.61,  -8.73,  -3.8 ,   0.94,
         1.69,   1.78,   3.04,   3.65,  -2.18,  -1.42,  -0.55,  -2.42,
        -2.85,   3.57,   3.15,   2.96,   2.44,   2.68,  -3.46, -13.47,
       -15.01, -17.46, -16.26, -10.7 ,  -9.8 ,  -7.43,  -1.36,  -9.03,
       -12.24, -18.68, -18.65,  -5.98,  -3.48,   7.64, -18.99,  -6.41,
        -4.29,   2.77,  -9.9 ,  -8.51,  -3.94,  -7.46,  -8.74,  -0.7 ,
        -0.58,  -5.09,  -5.88,  -8.99, -11.58, -12.46, -13.64,  -9.65,
       -12.2 , -11.28,  -8.69,  -8.67,  -1.38,   0.22,   2.98,   0.97,
         0.72,   1.43,  -0.7 ,  -2.21,  -2.78,  -3.93,  -4.93,  -5.24,
        -9.53,  -9.5 ,   0.68,   0.85,  -5.17,  -6.49,  -1.86,   2.54,
         2.75,   5.33,   0.61,  -1.  ,  -3.36,   5.32,   5.05,   4.56,
         5.36,   4.5 ,   5.06,   3.23,   0.78,   5.92,   8.12,   6.33,
         5.02,   8.56,   4.6 ,   7.62,   5.94,   7.5 ,  10.  ,   7.85,
      

# Дополнительно

#### Задание 1.

Создайте вектор из 100 чисел x = [1, ... , ... , ..., 137].

len(x) == 100

In [61]:
vec = np.linspace(1, 137, 100)
vec

array([  1.        ,   2.37373737,   3.74747475,   5.12121212,
         6.49494949,   7.86868687,   9.24242424,  10.61616162,
        11.98989899,  13.36363636,  14.73737374,  16.11111111,
        17.48484848,  18.85858586,  20.23232323,  21.60606061,
        22.97979798,  24.35353535,  25.72727273,  27.1010101 ,
        28.47474747,  29.84848485,  31.22222222,  32.5959596 ,
        33.96969697,  35.34343434,  36.71717172,  38.09090909,
        39.46464646,  40.83838384,  42.21212121,  43.58585859,
        44.95959596,  46.33333333,  47.70707071,  49.08080808,
        50.45454545,  51.82828283,  53.2020202 ,  54.57575758,
        55.94949495,  57.32323232,  58.6969697 ,  60.07070707,
        61.44444444,  62.81818182,  64.19191919,  65.56565657,
        66.93939394,  68.31313131,  69.68686869,  71.06060606,
        72.43434343,  73.80808081,  75.18181818,  76.55555556,
        77.92929293,  79.3030303 ,  80.67676768,  82.05050505,
        83.42424242,  84.7979798 ,  86.17171717,  87.54

#### Задание 2.
Даны векторы


`a = [1, 3, 7]`

`b = [2, -1, 5]`


Найдите скалярное произведение векторов **2a** и **-b**.

In [67]:
a = np.array([1, 3, 7])
b = np.array([2, -1, 5])

In [64]:
np.dot(2 * a, b * (-1))

np.int64(-68)

#### Задание 3*.

Вам дан вектор *a* = [1, 2, 5, 10]

Превратите вектор *a* в [0, 4, 0, 20] в одну строчку. Да, нужно угадать формулу.

In [69]:
a = np.array([1, 2, 5, 10])
a = a * (np.arange(len(a)) % 2) * 2
a

array([ 0,  4,  0, 20])

#### Задание 4**.
1. Выбрать все чётные строки матрицы A.
2. Составить одномерный массив из всех не делящихся на 3 элементов нечетных столбцов А.
3. Посчитать сумму диагональных элементов A.

In [128]:
# пример превращения вектора в двумерную матрицу (таблицу)
A = np.arange(120).reshape(10, -1)
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [129]:
# Выбрать все четные строки матрицы A.
del_ = np.arange(0, A.shape[0], 2)
A = np.delete(A, del_, axis=0)
A

array([[ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [130]:
# Составить одномерный массив
# из всех не делящихся на 3 элементов нечетных столбцов А.
_del_ = np.arange(0, A.shape[1], 2)
A = np.delete(A, _del_, axis=1)
A.reshape(-1)
A = A[A % 3 != 0]
A

array([ 13,  17,  19,  23,  37,  41,  43,  47,  61,  65,  67,  71,  85,
        89,  91,  95, 109, 113, 115, 119])

In [131]:
A = np.arange(120).reshape(10, -1)
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [133]:
# Посчитать сумму диагональных элементов A.
np.diagonal(np.fliplr(A)).sum() + np.diagonal(A).sum()

np.int64(1190)

# Не забудь сдать ноутбук с выполненным заданием!