<a href="https://colab.research.google.com/github/potopinc/colab/blob/main/ML_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Введение в NumPy (Занятие 3)



**NumPy** — библиотека языка Python, позволяющая [удобно] работать с многомерными массивами и матрицами и содержащая математические функции.

- Быстрые векторные операции:
    - переформатирование данных;
    - очистка/удаление дубликатов;
    - выборка подмножества;
    - фильтрация.
- Описательные статистики, агрегирование.
- Объединения и соединения разнородных данных.
- Выражения-массивы для условной логики.
- Групповое применение функций.

 [numpy](http://www.numpy.org)


In [1]:
# импорт библиотеки - самое начало!
import numpy as np

Основной тип данных - многомерный массив элементов одного типа — [numpy.ndarray] — контейнер для хранения больших наборов данных.

Одномерный массив называем **ВЕКТОР**.

In [5]:
# вектор из обычного списка
vec = np.array([1, 2, 3])
vec

array([1, 2, 3])

In [11]:
# длина массива по каждой из осей
vec.shape


(3,)

In [6]:
# тип элемента массива
vec.dtype

dtype('int64')

## Создание массивов

* Передача итерируемого объекта в качестве параметра функции array (можно также явно указать тип элементов):

In [12]:
q = np.array([0, 10, 1], dtype=float)
q

array([ 0., 10.,  1.])

* Создание массивов специального вида при помощи функций:

In [25]:
row = 5
colums = 9
shape = (row, colums)
q = np.ones(shape)
q

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

* Создание последовательностей при помощи функций arange (в качестве парметров принимает левую и правую границы последовательности и **шаг**) и linspace (принимает левую и правую границы и **количество элементов**):

In [32]:
start, stop, step = 0.5, 20.1, 0.4
np.arange(start, stop, step)

array([ 0.5,  0.9,  1.3,  1.7,  2.1,  2.5,  2.9,  3.3,  3.7,  4.1,  4.5,
        4.9,  5.3,  5.7,  6.1,  6.5,  6.9,  7.3,  7.7,  8.1,  8.5,  8.9,
        9.3,  9.7, 10.1, 10.5, 10.9, 11.3, 11.7, 12.1, 12.5, 12.9, 13.3,
       13.7, 14.1, 14.5, 14.9, 15.3, 15.7, 16.1, 16.5, 16.9, 17.3, 17.7,
       18.1, 18.5, 18.9, 19.3, 19.7])

In [33]:
np.linspace(start, stop)

array([ 0.5,  0.9,  1.3,  1.7,  2.1,  2.5,  2.9,  3.3,  3.7,  4.1,  4.5,
        4.9,  5.3,  5.7,  6.1,  6.5,  6.9,  7.3,  7.7,  8.1,  8.5,  8.9,
        9.3,  9.7, 10.1, 10.5, 10.9, 11.3, 11.7, 12.1, 12.5, 12.9, 13.3,
       13.7, 14.1, 14.5, 14.9, 15.3, 15.7, 16.1, 16.5, 16.9, 17.3, 17.7,
       18.1, 18.5, 18.9, 19.3, 19.7, 20.1])

## Базовые операции

* Базовые арифметические операции над массивами выполняются поэлементно.

In [34]:
q = np.array([2, 4, 6])
qq = np.array([5, 8, 10])
q + qq

array([ 7, 12, 16])

In [35]:
q * qq

array([10, 32, 60])

In [36]:
q / qq

array([0.4, 0.5, 0.6])

In [37]:
q - qq

array([-3, -4, -4])

Для выполнения скалярного произведения необходимо использовать функцию dot.

In [42]:
q.dot(qq)

np.int64(102)

## Индексация

Для доступа к элементам может использоваться много различных способов, рассмотрим основные.

In [49]:
q[-1]

np.int64(6)

### Индексация

In [51]:
q[0]

np.int64(2)

### Индексация списком индексов

In [50]:
q[[-1, 0, 1]]

array([6, 2, 4])

### Логическая индексация

In [56]:
step = 1
start = 0
q = np.arange(start, stop, step, dtype=int)
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [58]:
q > 6

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [59]:
q[q > 6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
q[(q % 2 == 0) & (q > 6)]

array([ 8, 10, 12, 14, 16, 18, 20])

### Срезы / slice

In [61]:
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [67]:
start, stop, step = 0, 15, 2
q[start:stop:step]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [63]:
q[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1,  0])

## Вектор случайных значений

In [70]:
min_, max_, count_ = 10, 90, 10
vec = np.random.randint(min_, max_, count_)
vec

array([70, 42, 87, 33, 25, 65, 78, 27, 44, 75])

In [72]:
max(vec), min(vec)

(np.int64(87), np.int64(25))

## Зачем?

Зачем необходимо использовать NumPy, если существуют стандартные списки/кортежи и циклы?

Причина заключается в скорости работы. Попробуем посчитать сумму поэлементых произведений 2 больших векторов.

In [ ]:
import time

In [74]:
x = np.random.normal(size = (100_000_000,))
y = np.random.normal(size = (100_000_000,))
x_list = list(x)
y_list = list(y)

In [75]:
%%time
sum((x_list[i] * y_list[i] for i in range(100_000_000)))

CPU times: user 17.5 s, sys: 1.56 ms, total: 17.5 s
Wall time: 17.6 s


np.float64(-2668.9702374950307)

In [76]:
%%time
x @ y

CPU times: user 195 ms, sys: 0 ns, total: 195 ms
Wall time: 104 ms


np.float64(-2668.9702374993535)